In [88]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from keras.layers import Input, Dense
from keras.models import Model
from keras.optimizers import adam
from sklearn.model_selection import train_test_split

In [89]:
data=pd.read_excel("/content/Main Data Set.xlsx")

In [90]:
data

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,gender,label
0,-371.82810,108.495650,11.329577,22.444440,22.374722,5.689639,-5.820382,-1.952239,-16.463146,6.061418,...,-2.383272,-1.047149,-5.113010,-3.650117,-3.092591,-1.955777,-4.405060,-4.580990,male,adult
1,-399.31082,112.921510,6.919172,21.663918,18.155872,7.181758,-1.518631,0.581832,-18.784006,3.909678,...,-1.837900,-0.798910,-4.694558,-4.464447,-1.893085,-2.912510,-4.858458,-4.174491,male,adult
2,-367.67980,100.844460,0.920031,23.759985,9.670633,1.539028,-6.678311,-0.632159,-19.383781,8.799910,...,-2.202147,-0.537667,-3.844402,-2.821896,-2.086511,-2.610275,-4.089844,-5.701215,male,adult
3,-355.13303,101.861480,0.237188,32.159462,22.914465,3.906355,-5.871533,-1.297926,-20.633438,7.027359,...,-1.725350,-0.643298,-3.470233,-2.856177,-2.057140,-1.870503,-4.755356,-4.600479,male,adult
4,-425.16406,129.036560,0.186828,16.686668,23.938263,10.088806,-2.028934,-2.977077,-19.282000,3.621475,...,-3.425826,0.476763,-4.416140,-2.720565,-2.072952,-1.341345,-5.566973,-4.696309,male,adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,-330.74442,119.453470,-28.931398,16.431282,-25.923940,-22.580963,-18.477665,-22.479776,0.922552,-7.602468,...,0.742409,-3.576027,-1.591279,-3.515108,-3.029455,-3.592587,-2.900054,0.754864,female,child
2996,-313.88834,99.268030,-26.273092,4.311078,-19.713417,-18.493284,-15.861244,-10.180239,-4.867939,-0.662536,...,1.392444,-0.948494,-3.438912,0.659637,-0.903038,-1.892453,-2.112316,-1.224023,female,child
2997,-324.29977,129.237520,-33.933000,11.158257,-17.881138,-26.475191,-13.977830,-16.337875,-0.353709,-4.651527,...,1.154832,-4.393998,-5.090885,-2.760841,-1.561349,-3.028061,-4.226657,3.758476,female,child
2998,-352.44968,148.348430,-32.924522,6.316973,-8.765810,-28.446260,-14.844326,-19.795837,-4.025840,-4.273027,...,0.961699,-3.170674,-4.107362,-6.001142,-4.654924,-3.437292,-3.550606,-0.757205,female,child
2999,-354.54044,97.072136,-24.854030,9.664994,-23.980673,-14.894958,-15.025388,-19.491266,-0.536067,-6.233265,...,3.516302,-1.918456,-0.355499,-1.424978,-2.336957,-1.454762,-6.149889,0.243947,female,child

In [95]:
x = data.iloc[:, :-2]
y = data.iloc[:, -1]
x

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,-371.82810,108.495650,11.329577,22.444440,22.374722,5.689639,-5.820382,-1.952239,-16.463146,6.061418,...,-0.184623,-2.057550,-2.383272,-1.047149,-5.113010,-3.650117,-3.092591,-1.955777,-4.405060,-4.580990
1,-399.31082,112.921510,6.919172,21.663918,18.155872,7.181758,-1.518631,0.581832,-18.784006,3.909678,...,-0.946463,-0.529916,-1.837900,-0.798910,-4.694558,-4.464447,-1.893085,-2.912510,-4.858458,-4.174491
2,-367.67980,100.844460,0.920031,23.759985,9.670633,1.539028,-6.678311,-0.632159,-19.383781,8.799910,...,1.907667,-1.688837,-2.202147,-0.537667,-3.844402,-2.821896,-2.086511,-2.610275,-4.089844,-5.701215
3,-355.13303,101.861480,0.237188,32.159462,22.914465,3.906355,-5.871533,-1.297926,-20.633438,7.027359,...,1.061948,-3.341648,-1.725350,-0.643298,-3.470233,-2.856177,-2.057140,-1.870503,-4.755356,-4.600479
4,-425.16406,129.036560,0.186828,16.686668,23.938263,10.088806,-2.028934,-2.977077,-19.282000,3.621475,...,0.215418,0.484430,-3.425826,0.476763,-4.416140,-2.720565,-2.072952,-1.341345,-5.566973,-4.696309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,-330.74442,119.453470,-28.931398,16.431282,-25.923940,-22.580963,-18.477665,-22.479776,0.922552,-7.602468,...,-2.470063,4.421223,0.742409,-3.576027,-1.591279,-3.515108,-3.029455,-3.592587,-2.900054,0.754864
2996,-313.88834,99.268030,-26.273092,4.311078,-19.713417,-18.493284,-15.861244,-10.180239,-4.867939,-0.662536,...,-2.227642,0.605481,1.392444,-0.948494,-3.438912,0.659637,-0.903038,-1.892453,-2.112316,-1.224023
2997,-324.29977,129.237520,-33.933000,11.158257,-17.881138,-26.475191,-13.977830,-16.337875,-0.353709,-4.651527,...,-0.028793,3.763042,1.154832,-4.393998,-5.090885,-2.760841,-1.561349,-3.028061,-4.226657,3.758476
2998,-352.44968,148.348430,-32.924522,6.316973,-8.765810,-28.446260,-14.844326,-19.795837,-4.025840,-4.273027,...,-3.241732,-0.987353,0.961699,-3.170674,-4.107362,-6.001142,-4.654924,-3.437292,-3.550606,-0.757205
2999,-354.54044,97.072136,-24.854030,9.664994,-23.980673,-14.894958,-15.025388,-19.491266,-0.536067,-6.233265,...,-2.224442,2.073195,3.516302,-1.918456,-0.355499,-1.424978,-2.336957,-1.454762,-6.149889,0.243947

In [96]:
y

0       adult
1       adult
2       adult
3       adult
4       adult
        ...
2995    child
2996    child
2997    child
2998    child
2999    child
Name: label, Length: 3000, dtype: object

In [97]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y

array([0, 0, 0, ..., 1, 1, 1])

In [98]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(x)
x_scaled = scaler.transform(x)
x_scaled = pd.DataFrame(x_scaled)
x_scaled

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,0.670138,0.586168,0.789807,0.569529,0.896276,0.606913,0.689202,0.666287,0.419384,0.778119,...,0.363010,0.359452,0.308980,0.388411,0.276964,0.323535,0.356386,0.419597,0.340556,0.203566
1,0.622623,0.612828,0.749603,0.561609,0.858494,0.622171,0.760771,0.713855,0.379224,0.741549,...,0.336053,0.413597,0.332691,0.401034,0.298709,0.278295,0.431761,0.355515,0.312453,0.228934
2,0.677310,0.540080,0.694918,0.582878,0.782504,0.564470,0.674928,0.691067,0.368845,0.824662,...,0.437042,0.372521,0.316855,0.414318,0.342888,0.369548,0.419606,0.375758,0.360095,0.133659
3,0.699003,0.546206,0.688693,0.668110,0.901110,0.588678,0.688351,0.678569,0.347221,0.794536,...,0.407118,0.313939,0.337584,0.408947,0.362332,0.367643,0.421452,0.425308,0.318844,0.202350
4,0.577925,0.709901,0.688234,0.511104,0.910279,0.651897,0.752281,0.647049,0.370606,0.736650,...,0.377164,0.449549,0.263653,0.465903,0.313177,0.375177,0.420458,0.460751,0.268537,0.196370
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0.741169,0.652175,0.422804,0.508512,0.463736,0.317828,0.478619,0.280951,0.720227,0.545891,...,0.282143,0.589083,0.444875,0.259815,0.459973,0.331036,0.360353,0.309963,0.433842,0.536551
2996,0.770311,0.530584,0.447036,0.385525,0.519355,0.359627,0.522149,0.511833,0.620028,0.663840,...,0.290720,0.453840,0.473137,0.393427,0.363960,0.562967,0.493973,0.423838,0.482669,0.413058
2997,0.752311,0.711111,0.377212,0.455005,0.535764,0.278007,0.553484,0.396244,0.698143,0.596044,...,0.368523,0.565755,0.462806,0.218220,0.278114,0.372940,0.452606,0.347775,0.351614,0.723992
2998,0.703642,0.826230,0.386405,0.405879,0.617396,0.257852,0.539068,0.331333,0.634600,0.602477,...,0.254838,0.397384,0.454409,0.280427,0.329223,0.192922,0.258212,0.320364,0.393518,0.442190
2999,0.700027,0.517356,0.459972,0.439853,0.481139,0.396422,0.536055,0.337050,0.694987,0.569162,...,0.290834,0.505861,0.565475,0.344104,0.524191,0.447155,0.403869,0.453155,0.232406,0.504667

In [99]:
encoding_dim = 20
input_data = Input(shape=(39,))
encoded = Dense(encoding_dim, activation='relu')(input_data)
decoded = Dense(39, activation='sigmoid')(encoded)

In [100]:
autoencoder = Model(input_data, decoded)
encoder = Model(input_data, encoded)

In [101]:
autoencoder.compile(optimizer='adam', loss='binary_crossentropy')

In [102]:

x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=42)

In [103]:
autoencoder.fit(x_train,
                x_train,
                epochs=50,
                batch_size=256,
                shuffle=True)

encoded_data = encoder.predict(x_test)

Epoch 1/50
10/10 [==============================] - 1s 4ms/step - loss: 0.7040
Epoch 2/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6933
Epoch 3/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6881
Epoch 4/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6849
Epoch 5/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6825
Epoch 6/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6805
Epoch 7/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6789
Epoch 8/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6775
Epoch 9/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6762
Epoch 10/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6751
Epoch 11/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6740
Epoch 12/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6730
Epoch 13/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6720
Epoch 14/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6711
Epoch 15/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6703
Epoch 16/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6694
Epoch 17/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6687
Epoch 18/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6680
Epoch 19/50
10/10 [==============================] - 0s 5ms/step - loss: 0.6673
Epoch 20/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6666
Epoch 21/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6660
Epoch 22/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6654
Epoch 23/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6649
Epoch 24/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6643
Epoch 25/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6638
Epoch 26/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6633
Epoch 27/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6628
Epoch 28/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6623
Epoch 29/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6618
Epoch 30/50
10/10 [==============================] - 0s 5ms/step - loss: 0.6614
Epoch 31/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6610
Epoch 32/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6605
Epoch 33/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6601
Epoch 34/50
10/10 [==============================] - 0s 5ms/step - loss: 0.6597
Epoch 35/50
10/10 [==============================] - 0s 5ms/step - loss: 0.6593
Epoch 36/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6589
Epoch 37/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6585
Epoch 38/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6581
Epoch 39/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6576
Epoch 40/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6572
Epoch 41/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6568
Epoch 42/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6565
Epoch 43/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6561
Epoch 44/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6558
Epoch 45/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6554
Epoch 46/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6551
Epoch 47/50
10/10 [==============================] - 0s 4ms/step - loss: 0.6548
Epoch 48/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6545
Epoch 49/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6542
Epoch 50/50
10/10 [==============================] - 0s 5ms/step - loss: 0.6540
19/19 [==============================] - 0s 2ms/step

In [104]:
'''from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Train a logistic regression classifier using the encoded data
classifier = LogisticRegression()
classifier.fit(encoded_data, y_test)

# Predict the labels using the classifier
predictions = classifier.predict(encoded_data)

# Calculate the accuracy of the predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)'''
from sklearn.linear_model import LogisticRegression

encoded_data = encoder.predict(x_test)

# Train a logistic regression classifier
classifier = LogisticRegression()
classifier.fit(encoded_data, y_test)

# Predict the label using the encoded representation
label_predictions = classifier.predict(encoded_data)
accuracy = accuracy_score(y_test, label_predictions)
print("Accuracy:", accuracy)

19/19 [==============================] - 0s 1ms/step
Accuracy: 0.9883333333333333

In [119]:
#4
input_sample=[0.577925,0.709901,0.688234,0.511104,0.910279,0.651897,0.752281,0.647049,0.370606,0.736650,0.669853,0.556179,0.420008,0.752727,0.759170,0.593053,0.562426,0.736432,0.504392,0.622027,0.364966,0.531934,0.221066,0.302269,0.287320,0.205320,0.268884,0.262020,0.213975,0.377164,0.449549,0.263653,0.465903,0.313177,0.375177,0.420458,0.460751,0.268537,0.196370]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 39, 1)
predictions = encoder.predict(input_sample)
predictions

predictions=classifier.predict(predictions)

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 33ms/step
[0]

In [106]:
#1500
input_sample=[0.872731, 0.411082, 0.480586, 1.000000, 0.253384, 0.528318, 0.296872, 0.394610, 0.502378,0.392042, 0.621543, 0.006626, 0.516975, 0.521456, 0.669484, 0.201321, 0.501754, 0.354544,0.311420, 0.320913, 0.236528, 0.187705, 0.124682, 0.319398, 0.362812, 0.542776, 0.778250,0.758794, 0.785707, 0.417236, 0.271772, 0.303650, 0.376029, 0.512281, 0.550409, 0.218163,0.291156, 0.418453, 0.608678]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 39, 1)
predictions = encoder.predict(input_sample)
predictions

predictions=classifier.predict(predictions)

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 33ms/step
[1]

In [107]:
#1499
input_sample=[0.697741, 0.525116, 0.545003, 0.692816, 0.457930, 0.359801, 0.461989, 0.315771, 0.490485, 0.428895, 0.669433, 0.294186, 0.603710, 0.517595, 0.442430, 0.583103, 0.683023, 0.505508, 0.506476, 0.355762, 0.302428, 0.292831, 0.054839, 0.251980, 0.439162, 0.346069, 0.717094, 0.573125, 0.496748, 0.452190, 0.556708, 0.442439, 0.613101, 0.533443, 0.404268, 0.594605, 0.536038, 0.537847, 0.326311]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 39, 1)
predictions = encoder.predict(input_sample)
predictions

predictions=classifier.predict(predictions)

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 25ms/step
[0]

In [108]:
#2599
input_sample=[0.712120,0.650542,0.366992,0.436288,0.428585,0.373965,0.687088,0.642749,0.686330,0.626207,0.468095,0.339787,0.584682,0.369466,0.463744,0.711811,0.482888,0.664246,0.481662,0.631933,0.521777,0.736818,0.678289,0.635984,0.828648,0.420239,0.479775,0.294975,0.133693,0.142501,0.396931,0.392093,0.430237,0.329627,0.330772,0.370938,0.354412,0.434149,0.383211]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 39, 1)
predictions = encoder.predict(input_sample)
predictions

predictions=classifier.predict(predictions)

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 25ms/step
[1]

In [109]:
#150
import numpy as np

input_sample = [0.697741, 0.525116, 0.545003, 0.692816, 0.457930, 0.359801, 0.461989, 0.315771, 0.490485, 0.428895, 0.669433, 0.294186, 0.603710, 0.517595, 0.442430, 0.583103, 0.683023, 0.505508, 0.506476, 0.355762, 0.302428, 0.292831, 0.054839, 0.251980, 0.439162, 0.346069, 0.717094, 0.573125, 0.496748, 0.452190, 0.556708, 0.442439, 0.613101, 0.533443, 0.404268, 0.594605, 0.536038, 0.537847, 0.326311]

input_sample = np.array(input_sample).reshape(1, 39, 1)
predictions = encoder.predict(input_sample)

predictions = classifier.predict(predictions)


threshold = 0.5
binary_predictions = (predictions > threshold).astype(int)

print(binary_predictions)

1/1 [==============================] - 0s 72ms/step
[0]

In [110]:
#1500
import numpy as np

input_sample = [0.872731, 0.411082, 0.480586, 1.000000, 0.253384, 0.528318, 0.296872, 0.394610, 0.502378,0.392042, 0.621543, 0.006626, 0.516975, 0.521456, 0.669484, 0.201321, 0.501754, 0.354544,0.311420, 0.320913, 0.236528, 0.187705, 0.124682, 0.319398, 0.362812, 0.542776, 0.778250,0.758794, 0.785707, 0.417236, 0.271772, 0.303650, 0.376029, 0.512281, 0.550409, 0.218163,0.291156, 0.418453, 0.608678]

input_sample = np.array(input_sample).reshape(1, 39, 1)
predictions = encoder.predict(input_sample)

predictions = classifier.predict(predictions)


threshold = 0.5
binary_predictions = (predictions > threshold).astype(int)

print(binary_predictions)

1/1 [==============================] - 0s 30ms/step
[1]

In [111]:
x_scaled.iloc[150]

0     0.831655
1     0.411186
2     0.559244
3     0.685691
4     0.709506
5     0.612764
6     0.499598
7     0.514133
8     0.483049
9     0.899541
10    0.629023
11    0.380120
12    0.777131
13    0.524901
14    0.832078
15    0.711080
16    0.502103
17    0.650106
18    0.517994
19    0.635600
20    0.336551
21    0.470930
22    0.220700
23    0.209610
24    0.304909
25    0.207724
26    0.311406
27    0.182513
28    0.247909
29    0.227411
30    0.354821
31    0.320541
32    0.315677
33    0.434150
34    0.538850
35    0.602915
36    0.598054
37    0.648223
38    0.508443
Name: 150, dtype: float64

In [112]:
#150
import numpy as np

input_sample = [0.831655, 0.411186, 0.559244, 0.685691, 0.709506, 0.612764, 0.499598, 0.514133, 0.483049, 0.899541, 0.629023, 0.380120, 0.777131, 0.524901, 0.832078, 0.711080, 0.502103, 0.650106, 0.517994, 0.635600, 0.336551, 0.470930, 0.220700, 0.209610, 0.304909, 0.207724, 0.311406, 0.182513, 0.247909, 0.227411, 0.354821, 0.320541, 0.315677, 0.434150, 0.538850, 0.602915, 0.598054, 0.648223, 0.508443]

input_sample = np.array(input_sample).reshape(1, 39, 1)
predictions = encoder.predict(input_sample)

predictions = classifier.predict(predictions)


threshold = 0.5
binary_predictions = (predictions > threshold).astype(int)

print(binary_predictions)

1/1 [==============================] - 0s 22ms/step
[0]

In [116]:
encoder.save('AutoEncoders_Age_Estimation.h5')

WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [126]:
from sklearn.ensemble import RandomForestClassifier
encoded_data = encoder.predict(x_test)

# Train a Random Forest Classifier
classifier = RandomForestClassifier()
classifier.fit(encoded_data, y_test)

# Predict the label using the encoded representation
label_predictions = classifier.predict(encoded_data)
accuracy = accuracy_score(y_test, label_predictions)
print("Accuracy:", accuracy)

19/19 [==============================] - 0s 2ms/step
Accuracy: 1.0

In [127]:
#4
input_sample=[0.577925,0.709901,0.688234,0.511104,0.910279,0.651897,0.752281,0.647049,0.370606,0.736650,0.669853,0.556179,0.420008,0.752727,0.759170,0.593053,0.562426,0.736432,0.504392,0.622027,0.364966,0.531934,0.221066,0.302269,0.287320,0.205320,0.268884,0.262020,0.213975,0.377164,0.449549,0.263653,0.465903,0.313177,0.375177,0.420458,0.460751,0.268537,0.196370]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 39, 1)
predictions = encoder.predict(input_sample)
predictions

predictions=classifier.predict(predictions)

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 23ms/step
[0]

In [128]:
#1500
input_sample=[0.872731, 0.411082, 0.480586, 1.000000, 0.253384, 0.528318, 0.296872, 0.394610, 0.502378,0.392042, 0.621543, 0.006626, 0.516975, 0.521456, 0.669484, 0.201321, 0.501754, 0.354544,0.311420, 0.320913, 0.236528, 0.187705, 0.124682, 0.319398, 0.362812, 0.542776, 0.778250,0.758794, 0.785707, 0.417236, 0.271772, 0.303650, 0.376029, 0.512281, 0.550409, 0.218163,0.291156, 0.418453, 0.608678]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 39, 1)
predictions = encoder.predict(input_sample)
predictions

predictions=classifier.predict(predictions)

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 34ms/step
[1]

In [129]:
#1499
input_sample=[0.697741, 0.525116, 0.545003, 0.692816, 0.457930, 0.359801, 0.461989, 0.315771, 0.490485, 0.428895, 0.669433, 0.294186, 0.603710, 0.517595, 0.442430, 0.583103, 0.683023, 0.505508, 0.506476, 0.355762, 0.302428, 0.292831, 0.054839, 0.251980, 0.439162, 0.346069, 0.717094, 0.573125, 0.496748, 0.452190, 0.556708, 0.442439, 0.613101, 0.533443, 0.404268, 0.594605, 0.536038, 0.537847, 0.326311]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 39, 1)
predictions = encoder.predict(input_sample)
predictions

predictions=classifier.predict(predictions)

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 92ms/step
[0]

In [130]:
#150
import numpy as np

input_sample = [0.831655, 0.411186, 0.559244, 0.685691, 0.709506, 0.612764, 0.499598, 0.514133, 0.483049, 0.899541, 0.629023, 0.380120, 0.777131, 0.524901, 0.832078, 0.711080, 0.502103, 0.650106, 0.517994, 0.635600, 0.336551, 0.470930, 0.220700, 0.209610, 0.304909, 0.207724, 0.311406, 0.182513, 0.247909, 0.227411, 0.354821, 0.320541, 0.315677, 0.434150, 0.538850, 0.602915, 0.598054, 0.648223, 0.508443]

input_sample = np.array(input_sample).reshape(1, 39, 1)
predictions = encoder.predict(input_sample)

predictions = classifier.predict(predictions)


threshold = 0.5
binary_predictions = (predictions > threshold).astype(int)

print(binary_predictions)

1/1 [==============================] - 0s 38ms/step
[0]

In [131]:
#2599
input_sample=[0.712120,0.650542,0.366992,0.436288,0.428585,0.373965,0.687088,0.642749,0.686330,0.626207,0.468095,0.339787,0.584682,0.369466,0.463744,0.711811,0.482888,0.664246,0.481662,0.631933,0.521777,0.736818,0.678289,0.635984,0.828648,0.420239,0.479775,0.294975,0.133693,0.142501,0.396931,0.392093,0.430237,0.329627,0.330772,0.370938,0.354412,0.434149,0.383211]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 39, 1)
predictions = encoder.predict(input_sample)
predictions

predictions=classifier.predict(predictions)

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 34ms/step
[1]

In [135]:
import joblib
joblib.dump(classifier,'AutoEncoder_Age_Estimation.joblib')

['AutoEncoder_Age_Estimation.joblib']